### ISSUE TITLE
Section 2 part 2 not storing

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#104]
"Details of other relevant planning documents" within section 2 is not storing

**Comment by DmitrySolyannik** [comment]
@PhilBarrett , @tony-shannon 
I've fixed this issue, it relates to key length of yottaDB, it reset this key length every time when I am restarting container. That's why I need manually setup new length after each restart of openEHR container. Need to discuss this issue with Rob, we should setup default length 1019, without manual changing

**Comment by PhilBarrett** [comment]
Tested and working fine, thank you.
