### ISSUE TITLE
NES - ReSPECT Bugs

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#53]
QA  testing - Friday 15/3 & 18/3

**Comment by PhilBarrett** [comment]
- [x] when selecting the time element for "date and time", the time doesn't render correctly and goes off screen (not responsive).
- [x] Please can this be proof read for spelling mistakes (i.e Mental instead of Mantal etc)
- [x] Section 10 autocompletes yet has a finish button
- [ ] Previous versions of the ReSPECT form should be read only - current I can edit the previous version
- [ ] The status displays as editing/in progress when going into a previous ReSPECT form version
 - [ ] No auto logout
- [x] screen bugs
![Screen Shot 2019-03-18 at 13.29.21.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206455fb6b7191a379ec0c2958415d4fbe5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecd5aff4ae44550a6133f6bf43b.png)
![Screen Shot 2019-03-18 at 13.29.30.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206455fb6b7191a379ec0c2958415c4ebe5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5f37aa984ecd5aff4ae44550a6133f6bf43b.png)
![Screen Shot 2019-03-15 at 20.00.45.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206455f66b7191a37aef0c2b51415b4bbe5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecd5aff4ae44550a6123662f43b.png)
![Screen Shot 2019-03-15 at 20.00.56.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206455f66b7191a37aef0c2b51415a48be5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecd5aff4ae44550a612376af43b.png)

@tony-shannon for awareness

**Comment by kuvakina** [comment]
> when selecting the time element for "date and time", the time doesn't render correctly and goes off screen (not responsive).

@PhilBarrett you mean this https://www.screencast.com/t/DfgQoCVPd6 ? I see that in mockups there is only date https://www.screencast.com/t/NqmO7o7iQ97 - should we also leave only date?



>  Can edit previous version
  Status when going into previous version

Could you add a bit more details, please?

**Comment by PhilBarrett** [comment]
> when selecting the time element for "date and time", the time doesn't render correctly and goes off screen (not responsive).

Both Date and time  are required as per the heading. This is how it renders for me in Chrome
![Screen Shot 2019-03-18 at 15 38 20](https://user-images.githubusercontent.com/12699244/54542641-1b172580-4994-11e9-829c-98e52e1688a4.png)
> Can edit previous version
Status when going into previous version

Descriptions updated, thanks

**Comment by kuvakina** [comment]
> Both Date and time are required as per the heading. This is how it renders for me in Chrome

In my Chrome, it works correctly so I didn't see it. Thank you

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

> when selecting the time element for "date and time", the time doesn't render correctly and goes off screen (not responsive).
Done, but react-datepicker plugin doesn't give possibility to change location of time selector (for example, to locate it below datepicker). For this reason we'll use time input instead of time selector:
![image](https://user-images.githubusercontent.com/39263134/54549996-e7e48e80-49b3-11e9-81d5-89cb22016a22.png)

> Please can this be proof read for spelling mistakes (i.e Mental instead of Mantal etc)
Done
![image](https://user-images.githubusercontent.com/39263134/54550091-0b0f3e00-49b4-11e9-9a12-e8371f2b49da.png)

> Section 10 autocompletes yet has a finish button
As my opinion it won't user friendly. Right now new version is created when user click on "Finish" in the last (10) section. If we remove this button, we have two ways to create a version:
1) When user leaves the page;
2) When user opens top row to edit.

Both cases are non-understandable for user.
In the first case used won't understand - what should he do to save all changes in the version.
In the second one - new versions will be created each time when user clicks on top row. What if user didn't want to create new version? 

For this reason I suggest rename the button:
![image](https://user-images.githubusercontent.com/39263134/54550539-d8b21080-49b4-11e9-90bd-76f56021b8a2.png)

Or "Save Version", or "Submit Version", or "Create version" - but version should be created ONLY in case user approve these changes.

**Comment by tony-shannon** [comment]
Just use " Save" for now please

**Comment by PhilBarrett** [comment]
@tony-shannon if section 10 is automatically completed, I don't think a button is needed here? Designs say not

**Comment by kuvakina** [comment]
@PhilBarrett then we have to send the form by clicking the button on 9th section, and then just go to 10th?  are there are changes that should be added to version form 10th section?

**Comment by PhilBarrett** [comment]
@kuvakina 

Also spotted two further typo's

Section 5 / 6. Attorney not attourney
Section 8 - in the dropdown menu - Coordinator not c-ordinator

**Comment by kuvakina** [comment]
@PhilBarrett fixed

**Comment by PhilBarrett** [comment]
For recent testing bugs 

https://youtu.be/tneJwxnbCug - 
https://www.screencast.com/t/cmppUIvlV

Very strange, because we have nowhere this pink colour, and this time it's info that "breathing" 

And after some more tests, it changed this way: https://www.screencast.com/t/leTVU7bZqa

And when  pointing on the record, it became pink https://www.screencast.com/t/hSEwH2g3eXP1

**Comment by kuvakina** [comment]
Here tests from Dima: https://www.screencast.com/t/cmppUIvlV . Very strange, because we have nowhere this pink colour, and this time it's info that "breathing" 

And after some more tests, it changed this way: https://www.screencast.com/t/leTVU7bZqa

And when Dima was pointing on the record, it became pink: https://www.screencast.com/t/hSEwH2g3eXP1

**Comment by kuvakina** [comment]
And one more video for example https://www.screencast.com/t/74dNq36z

Here again showed oval menu, and moved buttons. Also it is ok, for button Cancel in contrast mode to stay as red?

**Comment by PhilBarrett** [comment]
Closing as remaining tasks in #54
