### ISSUE TITLE
NES - ReSPECT Bugs review April

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#80]
- [x] Section 1 Street address isn't displaying **BS**
- [x] Section 1 remove status and date when creating new version
- [x] Section 3 slider not saving
- [x] Section 4 date picker error **BS**
- [x] Section 4 slider not saving
- [x] Section 7 date and time format
- [x] Section 7  second clinical signature can be removed from the UI
- [x] Section 8 not saved - PB to check
- [x] Section 9 date reviewed
- [x] Section 9 not saving
- [x] Section 10 remove status
- [x] Publish - dates incorrect and showing as 1970 date (see screenshot)
- [x]  DOB is showing in incorrect  format (US) in MPV and patient header
- [x] Date completed all showing incorrect values 

![Screen Shot 2019-04-24 at 17.58.14.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77276456f76b7191a379e80c2e59415e4abe5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecd5ef749e44f56a6113361f43b.png)

PDF Kit
- [x] date completed is empty
- [x] Section 4 not clear on what has been selected **See #59 **
- [x] Section 6, part 2 not saving
 - [x] Section 7 signatures not saving
 - [x] Section 9 not populating

**Server side issues**
- [x] Section 4 "..." in clinical signature - **EtherCIS issue with fields not available to record**
- [x] Section 4 clinical signature and date not saved 
- [x] Author showing as Jonty Shannon (incorrect) 
- [x] Section 6 Names not recorded/saved **YottaDB related issue**
- [x] Section 2 part 2 not saved **YottaDB related issue**

**Comment by PhilBarrett** [comment]
![Screen Shot 2019-04-24 at 10.41.36.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77276456f76b7191a379ef0c2f50415c48be5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5f37aa984ecd5ef74be14f51a3153e66f43b.png)

**Comment by PhilBarrett** [comment]
Responsive issue
![Screen Shot 2019-04-24 at 11.15.35.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77276456f76b7191a379ee0c2a54415c4bbe5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecd5ef74be04d56a6143162f43b.png)

**Comment by BogdanScherban** [comment]
@PhilBarrett @tony-shannon 
Few moments about this issue:

> Section 1 Street address isn't displaying

Street address is displayed, but address line 2 field is empty. Why?
Because I get this info from response to mpi/Patient/{id}:
![image](https://user-images.githubusercontent.com/39263134/56657571-0ddf0c00-66a1-11e9-9218-ab14f746ffa1.png)

Total street address is returned in the marked element.
Suggest to move this field generally - we save it nowhere.


> Section 2 part 2 not saved

Server side doesn't save this field.

> Section 4 slider not saving

@tony-shannon said, that we should save only string values like "PrioritisingSustainingLife" or "PrioritisingComfort". And doesn't save numbers like 17, 27, 58 etc. 
For this reason, when I want to review info about version, server returns me string "PrioritisingSustainingLife" or "PrioritisingComfort". I show position 5% in the first case (left position) or position 95% in the second one (right position).


>  Section 7 not saved - Need to discuss with TS as it is on the form

The reason is server side doesn't save more than one value in signatures array. Look, this is body of me PUT-request:
![image](https://user-images.githubusercontent.com/39263134/56656175-75935800-669d-11e9-85d4-db2612b10bd8.png)

And this is result of GET for this version:
![image](https://user-images.githubusercontent.com/39263134/56656242-a2476f80-669d-11e9-95a4-7af5d399394f.png)

So, server didn't save 2 and 3 items of array. This issue should be solved at the server side.


>  Section 8 not saved

Server side saves all values which client side sends. A
![image](https://user-images.githubusercontent.com/39263134/56656425-24379880-669e-11e9-9385-b57a31bb5189.png)

**Comment by kuvakina** [comment]
@PhilBarrett @tony-shannon 
Also re Section 8 - Other details:
right now we don't see this field in PDF because in Sections it's type is text area, and for PDF it should be a field.

@PhilBarrett suggested to change it to fields also. And also add this as extra column in the table @BogdanScherban can you please give more info re this?

**Comment by BogdanScherban** [comment]
to @kuvakina comment:

We can add details field to array. But in this case Dima or Alexey should do the same changes at the server side and in the database. And Respect JSON will be changed too.

**Comment by PhilBarrett** [comment]
Thanks for the updates, is Dima working with Bogdan on these, picking up the server side issues?

**Comment by kuvakina** [comment]
@PhilBarrett Dima updates nes/yottaDB/docker and them he can test some of the issues above and tell if they are done

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett Could you please comment re Bogdan's suggestions:

> Section 1 Street address isn't displaying

Street address is displayed, but address line 2 field is empty. Why?
Because I get this info from response to mpi/Patient/{id}:
Total street address is returned in the marked element.

-> **Suggest to move this field generally - we save it nowhere.**



> Section 4 slider not saving

@tony-shannon said, that we should save only string values like "PrioritisingSustainingLife" or "PrioritisingComfort". And doesn't save numbers like 17, 27, 58 etc.
For this reason, when I want to review info about version, server returns me string "PrioritisingSustainingLife" or "PrioritisingComfort". I show position 5% in the first case (left position) or position 95% in the second one (right position).

-> **Should we change this?**

> Section 8 not saved

Server side saves all values which client side sends. A

-> **Should we add Other detail as a column in table(saved)?**

**Comment by kuvakina** [comment]
Also Bogdan remover statuses from Sections 1 and 10
![2019-04-24_1544](https://user-images.githubusercontent.com/40596171/56660334-ff482300-66a7-11e9-96fa-30ebd39eec97.png)

**Comment by BogdanScherban** [comment]
These issues were done:

>  Section 1 remove status
>  Section 3 slider not saving
>  Section 7 date and time format
>  Section 10 remove status
>  Section 9 date reviewed
>  Publish - dates incorrect and showing as 1970 date (see screenshot)
> LOW Responsive view brings back old patient banner (see screenshot)

These issues because data isn't saved on the server side:

> Section 4 "..." in clinical signature - EtherCIS issue with fields not available to record
> Section 4 clinical signature and date not saved
> Author showing as Jonty Shannon (incorrect)
> Section 6 Names not recorded/saved

**Comment by PhilBarrett** [comment]
regarding
>- [ ] Section 1 Street address isn't displaying

> Street address is displayed, but address line 2 field is empty. Why?
Because I get this info from response to mpi/Patient/{id}:
image

>Total street address is returned in the marked element.

A number of addresses have two lines for their address i.e.

House name 
Street name
City
County
Postcode

So the MPI would need to cater for this. @tony-shannon one for the backlog I believe at this time.

**Comment by PhilBarrett** [comment]
Section 4 -Clinical signature needs to be added to template. Interim, use logged in username

**Comment by BogdanScherban** [comment]
Done
> LOW Responsive view brings back old patient banner (see screenshot)
> Section 1 Street address isn't displaying BS
> Section 4 not clear on what has been selected **See #59 **
>  Section 4 date picker error BS

**Comment by kuvakina** [comment]
@BogdanScherban for "Section 4 slider not saving" needs to be a binary choice:
0 all the way to the left  OR 100 all the way to the right

Also could you please fix this one:
Section 4 Isn't clear enough for such an important part of the form. X needs to be lower and larger and it needs a large circle around it really, to really emphasise the choice
